import type { Metadata } from 'next'
import { Onest } from 'next/font/google'
import './globals.css'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { NavBar } from '@/components/nav-bar'

const font = Onest({ subsets: ['latin'], weight: ['400', '500', '600', '700'] })

export const metadata: Metadata = {
  title: 'PagePal',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={font.className}>
        <ThemeProvider
          attribute='class'
          defaultTheme='dark'
          enableSystem={false}
          storageKey='pagepal-theme'
        >
          <NavBar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
